import Head from 'next/head'
import { useEffect, useState } from 'react'
import {supabase} from '../supabaseClient'
import Meal from "../components/Meal"
import Spinner from '../components/Spinner'

export default function Home() {

  const [meals, setMeals] = useState([])

  useEffect(() => {
    getMeals()
  }, [])

  const getMeals = async () => {
    try {
      const {data,error} = await supabase.from("meals").select().order('created_at',{ascending:false})
      setMeals(data)
    } catch (error) {
      alert(error)
    }
  }
  
  const arrMeals = meals.map(meal => <Meal key={meal.id} meal={meal}/>)

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {arrMeals.length == 0 ? <Spinner /> : arrMeals}
    </div>
  )
}
